How to start
vidible/OneMobileSDK-playground-ios pull request #1
Opened 2017-01-27 14:37 UTC by AlexeyDemedetskiy

@MarkGerl, @skalozubov, @AndriiMoskvin 

Please take a look at initial version of usage guide of `OneSDK` object.

2017-01-27 15:00 UTC, AndriiMoskvin commented on Usage guide.md
> +Migration note
in addtion we should have sections like - how it was before and how to achieve the same result with new SDK.

2017-01-30 13:50 UTC, AlexeyDemedetskiy commented on Usage guide.md
> +Migration note
Can you add some examples?

2017-01-30 14:14 UTC, AndriiMoskvin commented on Usage guide.md
> +Migration note
@AlexeyDemedetskiy  I've pushed example.

2017-02-01 15:29 UTC, AndriiMoskvin requested changes

2017-02-01 15:29 UTC, AndriiMoskvin commented on Podfile
> +pod 'OneMobileSDK-Swift3(ObjC)
`ObjC`?
`pod 'OneMobileSDK-Swift3'`

2017-02-01 15:29 UTC, AlexeyDemedetskiy commented on Podfile
> +pod 'OneMobileSDK-Swift3(ObjC)
Yep.

2017-02-01 16:34 UTC, merged