Added tvOS with multiple players template
vidible/OneMobileSDK-playground-ios pull request #14
Opened 2017-06-14 10:52 UTC by OleksandrPavliuk

2017-06-14 14:21 UTC, AndriiMoskvin requested changes

2017-06-14 14:21 UTC, AndriiMoskvin commented on Examples/tvOSMultiplePlayersTemplate/tvOSMultiplePlayersTemplate/AppDelegate.swift
> +        // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or whe
Drop commented code.

2017-06-14 14:21 UTC, AndriiMoskvin commented on Examples/tvOSMultiplePlayersTemplate/tvOSMultiplePlayersTemplate/PlayersCollectionViewController.swift
> +//
Replace these comment lines with:
```
//  Copyright © 2017 One by Aol : Publishers. All rights reserved.
```

2017-06-14 14:21 UTC, AndriiMoskvin commented on Examples/tvOSMultiplePlayersTemplate/tvOSMultiplePlayersTemplate/PlayersCollectionViewController.swift
> +            _ = systemPlayerViewController.player?.addObserver({ (observer) in
Why not `player.addObserver`?
Why `props` is named as `observer`?

2017-06-14 14:21 UTC, AndriiMoskvin commented on Examples/tvOSMultiplePlayersTemplate/tvOSMultiplePlayersTemplate/ViewController.swift
> +        playersCollectionViewController.playersQuantity = button.tag
Using `button.tag` as a data transfer object is a bad idea. Instead it should be explicitly and clearly specified.

2017-06-14 14:21 UTC, AndriiMoskvin commented on Examples/tvOSMultiplePlayersTemplate/tvOSMultiplePlayersTemplate/PlayersCollectionViewController.swift
> +
Drop these line breaks between single methods.

2017-06-14 14:21 UTC, AndriiMoskvin commented on Examples/tvOSMultiplePlayersTemplate/tvOSMultiplePlayersTemplate/PlayersCollectionViewController.swift
> +    override func awakeFromNib() {
Can this method be dropped?

2017-06-14 15:05 UTC, AndriiMoskvin requested changes

2017-06-14 15:05 UTC, AndriiMoskvin commented on Examples/tvOSMultiplePlayersTemplate/tvOSMultiplePlayersTemplate/PlayersCollectionViewController.swift
> +            let index = self.playerControllers.count - 1
Why not use ```playerControllers.index(of: systemPlayerViewController)```?

2017-06-14 15:05 UTC, AndriiMoskvin commented on Examples/tvOSMultiplePlayersTemplate/tvOSMultiplePlayersTemplate/ViewController.swift
> +    override func viewDidLoad() {
Drop empty method.

2017-06-14 15:05 UTC, AndriiMoskvin commented on Examples/tvOSMultiplePlayersTemplate/tvOSMultiplePlayersTemplate/ViewController.swift
> +    @IBOutlet weak var tenPlayersButton: UIButton!
Outlets never used - what is the reason of having them>

2017-06-14 15:09 UTC, AndriiMoskvin commented
Where this commit came from - 

Merge branch 'AOMSDK-1197/tvOS-with-multiple-players' of https://github.com/vidible/OneMobileSDK-playground-ios into AOMSDK-1197/tvOS-with-multiple-players

d45b8ed

2017-06-14 15:16 UTC, AndriiMoskvin requested changes

2017-06-14 15:16 UTC, AndriiMoskvin commented on Examples/tvOSMultiplePlayersTemplate/tvOSMultiplePlayersTemplate/PlayersCollectionViewController.swift
> +            playerCell.contentView.addSubview(playerVC.view)
Adding controller like this violates rules described in:
https://developer.apple.com/library/content/featuredarticles/ViewControllerPGforiPhoneOS/ImplementingaContainerViewController.html

2017-06-14 15:16 UTC, AndriiMoskvin commented on Examples/tvOSMultiplePlayersTemplate/tvOSMultiplePlayersTemplate/PlayersCollectionViewController.swift
> +            playerCell.contentView.superview.map {$0.removeFromSuperview() }
What is the purpose of this code?

2017-06-14 15:32 UTC, OleksandrPavliuk commented on Examples/tvOSMultiplePlayersTemplate/tvOSMultiplePlayersTemplate/PlayersCollectionViewController.swift
> +            let index = self.playerControllers.count - 1
We already know that needed index it's index of last object in array, also call `index(of...` will take CPU resources.

2017-06-14 15:57 UTC, AndriiMoskvin requested changes

2017-06-14 15:57 UTC, AndriiMoskvin commented on Examples/tvOSMultiplePlayersTemplate/tvOSMultiplePlayersTemplate/PlayersCollectionViewController.swift
> +        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "PlayersCollectionCellId", for: indexPath)
Use `guard let cell = ...`

2017-06-14 15:58 UTC, AndriiMoskvin commented on Examples/tvOSMultiplePlayersTemplate/tvOSMultiplePlayersTemplate/PlayersCollectionViewController.swift
> +            if let collection = self.collectionView {
Could be replaced with:
`collectionView?.reloadItems(at: [IndexPath(row: index, section: 0)])`

2017-06-19 18:34 UTC, AndriiMoskvin requested changes

2017-06-19 18:34 UTC, AndriiMoskvin commented on Examples/tvOSMultiplePlayersTemplate/tvOSMultiplePlayersTemplate/PlayersCollectionViewController.swift
> +            self.provider.getSDK()
Still we are requesting SDK several times, instead of getting it once and reusing for other players

2017-06-19 18:57 UTC, AndriiMoskvin requested changes

2017-06-19 18:57 UTC, AndriiMoskvin commented on Examples/tvOSMultiplePlayersTemplate/tvOSMultiplePlayersTemplate/PlayersCollectionViewController.swift
> +            self.provider.getSDK()
For some reasons you are requesting players twice, once in `viewDidLoad` and once here.

2017-06-20 15:42 UTC, AndriiMoskvin requested changes

2017-06-20 15:42 UTC, AndriiMoskvin commented on Examples/tvOS Players CollectionView/tvOS Players CollectionView/PlayersCollectionViewController.swift
> +        var playbackIsReady: Bool
What is the reason of storing `isPlaybackReady` in the model?
The value could be directly used without storing it in `Model`.

2017-06-20 15:45 UTC, OleksandrPavliuk commented on Examples/tvOS Players CollectionView/tvOS Players CollectionView/PlayersCollectionViewController.swift
> +        var playbackIsReady: Bool
We need to have all `isPlaybackReady` values in array to combine label text.

2017-06-20 15:46 UTC, AndriiMoskvin commented on Examples/tvOS Players CollectionView/tvOS Players CollectionView/PlayersCollectionViewController.swift
> +        var playbackIsReady: Bool
Why not to combine it one by one as soon as they arrive?

2017-06-20 16:10 UTC, AndriiMoskvin approved these changes

2017-06-20 16:45 UTC, merged