Add template with picture in picture functionality
vidible/OneMobileSDK-playground-ios pull request #20
Opened 2017-08-08 09:01 UTC by OleksandrPavliuk

https://jira.ops.aol.com/browse/OMSDK-86

2017-08-08 12:37 UTC, AndriiMoskvin requested changes

2017-08-08 12:37 UTC, AndriiMoskvin commented on Examples/Picture in picture Integration/Picture in picture Integration/AppDelegate.swift
> +//
Drop comments - except Copyright.

2017-08-08 12:37 UTC, AndriiMoskvin commented on Examples/Picture in picture Integration/Picture in picture Integration/AppDelegate.swift
> +         Setup audio session for picture in picture playback.
Add link to official Apple documentation.

2017-08-08 12:37 UTC, AndriiMoskvin commented on Examples/Picture in picture Integration/Picture in picture Integration/ViewController.swift
> +//
Drop comments - except Copyright.

2017-08-08 12:37 UTC, AndriiMoskvin commented on Examples/Picture in picture Integration/Picture in picture Integration/AppDelegate.swift
> +            print("Audio session setCategory failed")
Instead of printing this error let's fail here with `precondition`.

2017-08-08 12:56 UTC, AndriiMoskvin commented
Drop deployment target to iOS 8.0.

2017-08-08 12:57 UTC, AndriiMoskvin commented
Please, add 2 screenshots that will demonstrate PiP mode (active and non-active) and README.md that will briefly describe this example.

2017-08-09 09:35 UTC, OleksandrPavliuk commented
Done

2017-08-09 16:39 UTC, AndriiMoskvin requested changes

2017-08-09 16:39 UTC, AndriiMoskvin commented on Examples/Picture in picture Integration/README.md
> +
Can you make this images smaller and put them in table?

2017-08-09 16:39 UTC, AndriiMoskvin commented on Examples/Picture in picture Integration/Podfile.lock
> +  - OneMobileSDK-Beta-Swift3
Still `Beta` here - should be 2.8 non-beta.

2017-08-09 16:41 UTC, AndriiMoskvin requested changes

2017-08-09 16:41 UTC, AndriiMoskvin commented on Examples/Picture in picture Integration/README.md
> +This example demonstrates how to get picture in picture playback of content video.  The example also demonstrates the configuration setup required by an application to be able to use picture in pictu
Split this text in 2 bullets:
- Demonstration of Picture-in-Picture functionality built in OneMobileSDK
... screenshots go here...
- Required configuration setup for the client app:
... configuration instructions ...

2017-08-09 17:11 UTC, OleksandrPavliuk commented on Examples/Picture in picture Integration/README.md
> +This example demonstrates how to get picture in picture playback of content video.  The example also demonstrates the configuration setup required by an application to be able to use picture in pictu
Done

2017-08-09 17:23 UTC, AndriiMoskvin approved these changes

2017-08-09 17:23 UTC, merged