Examples for Tutorial 2 – Custom UX
vidible/OneMobileSDK-playground-ios pull request #40
Opened 2017-12-22 13:46 UTC by BogdanBilonog

Need to add examples for Tutorial 2 – Custom UX from [doc](https://docs.google.com/document/d/19cVTBPadBSYWdEf6f933mdOQCrPgMU_VdG1EaTNyb2c/edit)

[JIRA Issue](https://jira.ops.aol.com/browse/OMSDK-520)

2017-12-22 14:14 UTC, AndriiMoskvin requested changes

2017-12-22 14:14 UTC, AndriiMoskvin commented on NewTutorials/Tutorial/Info.plist
> +		<key>NSAllowsArbitraryLoads</key>
Why do you need this enabled? - We have https everywhere.

2017-12-22 14:14 UTC, AndriiMoskvin commented on NewTutorials/Tutorial/PlayerViewControllerWrapper.swift
> +        var controlsColor: UIColor?
These fields look like separate struct inside `Props`.

2017-12-22 14:14 UTC, AndriiMoskvin commented on NewTutorials/Tutorial/PlayerViewControllerWrapper.swift
> +                    }
```
else {
// unhide them?
}```

2017-12-22 14:14 UTC, AndriiMoskvin commented on NewTutorials/Tutorial/SetupTutorials.swift
> +    vc.show(viewController: wrapper)
Function `bind` shows view controller, seriously?

2017-12-22 14:14 UTC, AndriiMoskvin commented on NewTutorials/Tutorial/TutorialsViewController.swift
> +        case ("PlayingVideos"): setupPlayingVideos(vc: vc)
Parenthesis `( )` not needed.

2017-12-22 14:14 UTC, AndriiMoskvin commented on NewTutorials/Tutorial/SetupTutorials.swift
> +func setupPlayingVideos(vc: TutorialCasesViewController) {
`vc` is a bad parameter name

2017-12-23 07:24 UTC, AndriiMoskvin requested changes

2017-12-23 07:24 UTC, AndriiMoskvin commented on NewTutorials/Tutorial/SetupTutorials.swift
> +    tutorialCasesViewController.show(viewController: wrapper)
Can wrapper be created inside this function?

2017-12-23 07:24 UTC, AndriiMoskvin commented on NewTutorials/Tutorial/SetupTutorials.swift
> +    tutorialCasesViewController.show(viewController: wrapper)
No reason to pass it each time to this function.

2017-12-23 07:24 UTC, AndriiMoskvin commented on NewTutorials/Tutorial/SetupTutorials.swift
> +    tutorialCasesViewController.show(viewController: wrapper)
The same about `TutorialCasesViewContoller` - maybe function `show` should be maid inside this class?

2017-12-23 07:25 UTC, AndriiMoskvin requested changes

2017-12-23 07:25 UTC, AndriiMoskvin commented on NewTutorials/Tutorial/PlayerViewControllerWrapper.swift
> +                    // Mudifing content props only if content video can be played
`guard let self = self else {  return props }`

2018-01-03 10:32 UTC, AndriiMoskvin submitted a review, later dismissed

2018-01-03 10:32 UTC, AndriiMoskvin commented on NewTutorials/Tutorial/PlayerViewControllerWrapper.swift
> +                    // Mudifing content props only if content video can be played
`Modifying`

2018-01-03 10:32 UTC, AndriiMoskvin commented on NewTutorials/Tutorial/PlayerViewControllerWrapper.swift
> +                    controls.live.dotColor = strongSelf.props.controls.liveDotColor
Can we make each of these snipppet as a function with self-descriptive name?

2018-01-03 10:33 UTC, AndriiMoskvin requested changes
☝️

2018-01-09 11:50 UTC, AndriiMoskvin requested changes

2018-01-09 11:50 UTC, AndriiMoskvin commented on NewTutorials/Tutorial/PlayerViewControllerWrapper.swift
> +                    // Mudifying content props only if content video can be played
`Modifying`

2018-01-09 11:58 UTC, BogdanBilonog commented on NewTutorials/Tutorial/PlayerViewControllerWrapper.swift
> +                    // Mudifying content props only if content video can be played
:disappointed_relieved:

2018-01-09 13:02 UTC, AndriiMoskvin approved these changes

2018-01-09 13:03 UTC, merged