Examples for Tutorial 5 – Playing videos on tvOS
vidible/OneMobileSDK-playground-ios pull request #42
Opened 2017-12-27 17:01 UTC by BogdanBilonog

Need to add examples for Tutorial 5 – Playing videos on tvOS(https://docs.google.com/document/d/19cVTBPadBSYWdEf6f933mdOQCrPgMU_VdG1EaTNyb2c/edit)

[JIRA Issue](https://jira.ops.aol.com/browse/OMSDK-523)

2018-01-03 13:03 UTC, AndriiMoskvin commented on NewTutorials/Tutorial/SetupTutorials.swift
> +        guard let wrapper = viewController as? PlayerViewControllerWrapper else { return }
Put this code at the top?

2018-01-03 13:05 UTC, AndriiMoskvin requested changes

2018-01-03 13:05 UTC, AndriiMoskvin commented on NewTutorials/Tutorial_tvOS/SetupTutorials.swift
> +        guard let wrapper = viewController as? SystemPlayerViewControllerWrapper else { return }
The same - put it at the top!

2018-01-03 13:05 UTC, AndriiMoskvin commented on NewTutorials/Tutorial_tvOS/SystemPlayerViewControllerWrapper.swift
> +                        guard let outputImage = filter.outputImage else { return }
Replace `$0` with descriptive name.

2018-01-04 15:23 UTC, AndriiMoskvin approved these changes

2018-01-09 13:06 UTC, closed without merging

2018-01-09 13:10 UTC, BogdanBilonog commented
Moved to https://github.com/aol-public/OneMobileSDK-playground-ios/pull/45