Examples for Tutorial 5 – Playing videos on tvOS
vidible/OneMobileSDK-playground-ios pull request #45
Opened 2018-01-09 13:09 UTC by BogdanBilonog

Need to add examples for Tutorial 5 – Playing videos on tvOS from [doc](https://docs.google.com/document/d/19cVTBPadBSYWdEf6f933mdOQCrPgMU_VdG1EaTNyb2c/edit)

[JIRA Issue](https://jira.ops.aol.com/browse/OMSDK-523)

2018-01-09 13:51 UTC, AndriiMoskvin requested changes
I'm stuck on initial screen - Player is not shown.

2018-01-09 13:55 UTC, BogdanBilonog commented
Try now

2018-01-10 11:56 UTC, AndriiMoskvin requested changes
We don't support any array/playlist based solutions on tvOS.
And 360 videos also.

2018-01-10 14:10 UTC, AndriiMoskvin approved these changes

2018-01-10 14:16 UTC, merged