Added example with custom seeker colors and fixed animations example
vidible/OneMobileSDK-playground-ios pull request #61
Opened 2018-08-22 12:07 UTC by RomanTysiachnik

## Changes 
- [x] Added example with custom colors of the seeker;
- [x] Fixed incorrect behavior of example with disabled animation;
- [ ] Updated Readme.

@aol-public/mobile-sdk-team Ready for review

2018-08-22 13:19 UTC, AndriiMoskvin submitted a review, later dismissed

2018-08-22 13:19 UTC, AndriiMoskvin commented on README.md
> +#### Seeker Custom Colors
Please, update the table of contents also.

2018-08-22 13:19 UTC, AndriiMoskvin commented on README.md
> +> [Animations Customization](https://github.com/aol-public/OneMobileSDK-playground-ios/tree/master/NewTutorials)
Why `Animations Customization`?

2018-08-22 14:49 UTC, AndriiMoskvin approved these changes

2018-08-22 15:50 UTC, AndriiMoskvin requested changes

2018-08-22 15:50 UTC, AndriiMoskvin commented on README.md
> +The latest update includes a new feature to set custom colors for each element of player's seeker, like current time, progress, cue points etc. It is also possible to set custom color only for one of
Reference which one update, please.

2018-08-23 11:37 UTC, AndriiMoskvin commented on README.md
> +The latest update includes a new feature to set custom colors for each element of player's seeker, like current time, progress, cue points etc. It is also possible to set custom color only for one of
@RomanTysiachnik ☝️

2018-08-23 12:27 UTC, AndriiMoskvin submitted a review, later dismissed

2018-08-23 12:27 UTC, AndriiMoskvin commented
Waiting for SDK release 2.28.

2018-08-27 15:27 UTC, MarkGerl commented
Looks good to me @RomanTysiachnik

2018-08-29 09:39 UTC, RomanTysiachnik commented
@AndriiMoskvin waiting for your review.

2018-08-29 09:41 UTC, AndriiMoskvin approved these changes

2018-08-29 09:43 UTC, merged