Added sample of ads only player with disabled controls and short video
vidible/OneMobileSDK-playground-ios pull request #66
Opened 2018-10-22 12:53 UTC by RomanTysiachnik

## Notes
In this test case, we've totally turned off controls for the content player. And the `video id`, that we use is very very short with a dark background, so it ends right after the ad is finished.
The player itself can be shown, for example, whenever the `isAdPlaying` value in `props` is `true`. 
This is an easy example of how it can be done, without doing any changes in our SDK.

## Demo
![ads-only-giph](https://user-images.githubusercontent.com/31652265/47293210-29922880-d612-11e8-855b-022fb992af44.gif)

2018-10-23 08:12 UTC, AndriiMoskvin requested changes
The ads only player on web has completely different API and not uses VRM at all.
There is no guarantee that VRM will return an ad - if not this will lead to very strange black screen flash.
Your player is ads only from UX perspective but not from business.

2018-10-23 09:30 UTC, RomanTysiachnik commented
Of course it is. I've added that example to show how it can be done without making specific changes in SDK.

2018-10-23 09:34 UTC, AndriiMoskvin commented
I don't think it is acceptable solution to be placed in tutorials.

2018-12-21 15:29 UTC, AndriiMoskvin commented
Closing this - can be reopened in future if needed. Branch will not be deleted.

2018-12-21 15:29 UTC, closed without merging